class_configs/nec_class_config.lua
- Add Necro LS spell lines
- Fix Necro Alliance ordering (it was backwards)
=> Add Necro Spell lines and small associated fixes

class_configs/bst_class_config.lua, class_configs/mag_class_config.lua, utils/rgmercs_utils.lua
All simple fixes, see commit messages for details
=> Minor fixes

class_configs/wiz_class_config.lua
Improved DPS section and spell gem choice. Added Snare and Rain usage. Improved DPS 5x over RGMercs macro at level 64
=> improve-dps--add-snare-add-rain

class_configs/brd_class_config.lua, modules/mez.lua, modules/movement.lua, utils/rgmercs_utils.lua
Still need to add more docs, but there's no known bugs remaining and 125 bard has been pretty well tested now across group grinds/missions/raids.
=> Bard update

class_configs/brd_class_config.lua
not RGMercUtils.SelfBuffCheck("Selo's Accelerato") and
=> check the buff exist in order to avoid spamming selo's sonata

class_configs/brd_class_config.lua
Changed ColdDotSong -> IceDotSong to prevent tooltip crash
=> ColdDotSong -> IceDotSong

class_configs/shm_class_config.lua
Shm class config:  Added AESlow count, AEMalo count, some checks on slow and malo casts, added that it will now use dicho and Canni AA(during combat) while in "heal" mode, added Epic use to a Healburn rotation and an option to turn on 3 DOTS use in Heal mode in HealDPS rotation added a check for Tala'tak to prevent loops of recasting while out of combat, added a mob% check for Turgurs to stop casting on mobs upon it dying. some other small shits i forget
=> shm class config

modules/pull.lua
If the MyPaths_Paths.lua is present then load a table for it.
if the zone has any paths then show a drop down to select from or use the original saved waypoints.
you can reload the paths file with a button click incase it any were edited or imported / added in MyPaths.
=> Support for MyPaths Paths in Farm Mode

class_configs/brd_class_config.lua
=> BRD: added enduring breath line and toggle

class_configs/dru_class_config.lua, class_configs/pal_class_config.lua, utils/rgmercs_named.lua, utils/rgmercs_utils.lua
[utils] Partial update of named.lua (corrections/additions), in the process of going zone-by-zone and making on the spot fixes as I play/travel. Moved some entries as I'm slowly aligning entries to be in expansion/ID order for ease of navigation and updates.
[PAL] Added setting to toggle doing cures.
[DRU] Added IsRezing Mode.
=> [utils] named.lua updates

class_configs/dru_class_config.lua, class_configs/mag_class_config.lua, class_configs/shm_class_config.lua, modules/class.lua, utils/rgmercs_config.lua, utils/rgmercs_utils.lua
[DRU, SHM] Added/fixed Twincast Heal Nukes (thanks Derple for the correction on TID).
[MAG] Added the ability to adjust the delay before autoinventory commands to suit various network environments.
=> Classes updates (DRU, SHM, MAG)

class_configs/wiz_class_config.lua
Added Spire of Arcanum to Burn
=> Wiz - Added Spire of Arcanum to Burn

class_configs/war_class_config.lua
Added Spire of the Warlord to Burn
=> WAR - Added Spire of the Warlord to Burn

class_configs/shd_class_config.lua
Added Spire of the Reavers to Burn
=> SHD - Added Spire of the Reavers to Burn

class_configs/shm_class_config.lua
Added Spire of Ancestors to Burn and HealBurn
=> SHM - Added Spire to Burn and healburn

class_configs/war_class_config.lua
Added Flash of Anger to fire in dps if HP < 30, same as in burn. Since our HP can drop fast even if we dont burn.
=> WAR - Flash of Anger

init.lua, modules/class.lua, utils/rgmercs_classloader.lua
added a button to copy the default class config to the custom configs folder and added the variable for FullConfig to the custom config.
this will generate the file for the user so they just need to edit it as they wish.
=> feat: create a custom class config from the base

class_configs/pal_class_config.lua, utils/rgmercs_named.lua
=> Update Paladin Ability Table for LS

class_configs/bst_class_config.lua
Swapped Maelstrom and Poison Bite to smooth gem use during leveling.
=> [BST] Minor Gem Swap

modules/charm.lua
added max lvl for Dire Charm
hide dire charm settings on bards since they don't have that aa.
=> Dire Charm settings

utils/rgmercs_utils.lua
when finding a target ignore charmed mobs.
adjusted announce handlers.
=> target check if charmed and adjusted announce handlers

class_configs/brd_class_config.lua
* now checks buff window first if not found defaults to 999.
* then it checks song window and if not found defaults to 0.
this way it works for all songs regardless of the window the buff appears in.
EB checks for feet wet or in thegrey. if toggled on.
=> tweak RefreshBuffSong Function

init.lua, utils/rgmercs_binds.lua, utils/rgmercs_config.lua
=> feat: minimize the window to a button of DerpleDog

class_configs/brd_class_config.lua
Reverted changes to fallback combat aria/warmarch, longrunbuff
=> [BRD] Prioritized Enduring Breath song if used

class_configs/shd_class_config.lua
Removed the requirement to wield a 2h for the blade Combat Ability
=> SHD - removed 2h check from 'Blade' Combat Ability

class_configs/dru_class_config.lua, class_configs/shd_class_config.lua
=> Update Dru spells to 125

modules/basic.lua, modules/charm.lua, modules/class.lua, modules/drag.lua, modules/experience.lua, modules/mez.lua, modules/movement.lua, modules/performance.lua, modules/pull.lua, modules/travel.lua
Moved module init/load/unload messages to the debug channel
=> chat spam reduction round 2

class_configs/mag_class_config.lua, class_configs/shd_class_config.lua
[SHD] Linked lifetaps to mana/burn checks in non-emergencies
[MAG] Added item check to stop epic spam.
=> SHD lifetap update, MAG epic update

class_configs/mag_class_config.lua, utils/rgmercs_utils.lua
Moved to pet management rotation to support targeting differences on emu servers.
=> [MAG] Mana conversion buff fix

utils/rgmercs_utils.lua
mq.TLO.Me.Song(1)() = Beguiler's Aura Effect
mq.TLO.Me.Aura(1)() = Beguilers Aura
=> fix for aura's where the ' is stripped out

class_configs/pal_class_config.lua
Added For Honor to pull abilities
=> PAL - Added For Honor line to pull-abilities

utils/rgmercs_classloader.lua
fixed the path passed to be the custom file not the backup. since we did the backup first.
=> fix: backup was being overwritten when creating the custom file.

class_configs/bst_class_config.lua
* Tied group buffs to new functions
* Added Unity buff and proper checks
=> [BST] Buff Updates

lib/lootnscoot/loot_hist.lua, lib/lootnscoot/loot_lib.lua, modules/loot.lua
also added /rgl lootreload command to reload loot settings file.
also of note `/lootutils` commands still work if you want to specify an item by name.
=> some cleanup on loot stuff

lib/lootnscoot/loot_lib.lua, modules/loot.lua, utils/rgmercs_logger.lua
added access to the lootnscoot settings directly from rgmercs. also can modify global items and your buy items.
=> Loot settings work

class_configs/clr_class_config.lua, class_configs/shd_class_config.lua, modules/movement.lua, utils/rgmercs_config.lua, utils/rgmercs_utils.lua
[config]
* Made a cleanup/organization pass on main settings.
[CLR]
* Moved Remedy and Complete Heal settings to the class config. Please note that you may need to adjust defaults for these settings if you had previously done so.
[movement]
* Move options for Priority Follow, Fellowship Insignia and Movement While Paused to the move module. Please note that you may need to adjust defaults for these settings if you had previously done so (note placed temporarily on startup).
[SHD]
Added options to configure Thought Leech use.
=> Settings Pass, SHD Thought Leech

class_configs/brd_class_config.lua, class_configs/bst_class_config.lua, class_configs/enc_class_config.lua, class_configs/mag_class_config.lua, class_configs/nec_class_config.lua, class_configs/pal_class_config.lua, class_configs/shd_class_config.lua, class_configs/shm_class_config.lua, utils/rgmercs_utils.lua
* Added DoPetCheck() to utils to fully break pet summoning and buffing away from DoBuffs
* Aligned and standardized Pet Summon and Buff rotation names
* Tied DoPetCheck() to these rotations to give invis/movement/etc protection
* [MAG] Sorted rotations slightly and moved some abilities between rotations to allow proper checks.
=> Pet Updates

class_configs/shd_class_config.lua, modules/basic.lua, modules/charm.lua, modules/class.lua, modules/contributors.lua, modules/drag.lua, modules/experience.lua, modules/faq.lua, modules/loot.lua, modules/mez.lua, modules/movement.lua, modules/performance.lua, modules/pull.lua, modules/travel.lua
this will show class related settings and their FAQ
=> added Class Specific FAQ section

modules/charm.lua, modules/faq.lua, modules/loot.lua
also cleaned up the layout some as it gets rather long.
=> added some more FAQ info

modules/faq.lua
/rgl exportwiki
Will dump the FAQ's by module and class into separate files within /config/WIKI
also dumps the Commands FAQ as well.
=> export faq to wiki command

class_configs/pal_class_config.lua, class_configs/war_class_config.lua
Also added clarity to "Summon Arrows" tooltips.
Fixes Issue #153
=> Added level check to Huntsman's Ethereal Quiver

class_configs/pal_class_config.lua
Added the missing low level PAL fury/weapon proc spells to the FuryProc section
=> Add low level PAL fury/weapon proc spells

init.lua, lib/lootnscoot/loot_lib.lua, modules/loot.lua
when setting a quest item with a quantity /rgl setitem quest|qty will work for the item on cursor.
=> popout loot window, fix for setitem commands

class_configs/Live - Beta/shm_class_config.lua, class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live/ber_class_config.lua, class_configs/Live/brd_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/clr_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Live/mag_class_config.lua, class_configs/Live/mnk_class_config.lua, class_configs/Live/nec_class_config.lua, class_configs/Live/pal_class_config.lua, class_configs/Live/rng_class_config.lua, class_configs/Live/rog_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Live/wiz_class_config.lua, class_configs/Project Lazarus/clr_class_config.lua, class_configs/Project Lazarus/dru_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/mnk_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua, class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/rng_class_config.lua, class_configs/Project Lazarus/rog_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, class_configs/Project Lazarus/wiz_class_config.lua
* Standardized Version Naming
* Added BETA config: SHM Live overhaul
* Added EXPERIMENTAL config: DRU Heal/HealDPS improvements
Please see forum post for more details!
=> Config Selection Update

class_configs/Live/brd_class_config.lua, class_configs/Project Lazarus/brd_class_config.lua
=> [BRD] Added Aria toggle option for pre-overhaste levels.

utils/rgmercs_binds.lua
/rgl pop console
/rgl pop debug
both will pop out the debug console
=> pop console command

class_configs/Live/enc_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua
May require special handling, stronger arguments for using than omitting.
=> [ENC] Added Rapture to MezSpell list

.vscode/settings.json, class_configs/Live/shd_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua
* You can now opt to use Leech Touch during burns on Live and Project Laz. We will still use it only as an emergency ability by default.
=> [SHD] Added configuration options for Leech Touch

class_configs/Live - Experimental/wiz_class_config.lua
* Aimed at modern spell sets and rotations starting at ~ level 115 (perhaps 110).
* This may be usable as low as 100, but you are likely to see progressively worse mana issues below the intended level range.
* Like other experimental configs, this is an as-is config that may eventually progress to a beta or a mode addition to the default. Options and such could be added at a later date.
* Feedback highly sought after, as my group and use case may not be the same as yours!
=> [WIZ] Added experimental config: Modern Era

lib/lootnscoot/loot_hist.lua, lib/lootnscoot/loot_lib.lua, modules/loot.lua
save the state for the loot report and loot console windows.
=> loot gui windows save state and have toggles.

class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
* [SHM] (Live, Laz) Added updated healing checks to pet rotations
* [DRU] (Experimental) Retrofit rotations with updated healing checks
=> Minor Healer Updates

.vscode/settings.json, class_configs/Live - Beta/war_class_config.lua, class_configs/Live - Experimental/clr_class_config.lua, class_configs/Live - Experimental/pal_class_config.lua
[CLR]
* Experimental heal mode config added. Major revamp.
* * Spell set is currently aimed at 100+ and likely will not work well at lower levels.
* * This config does not contain a hybrid mode.
* * Feedback is desired on specific options and gem selections.
[PAL]
* Experimental tank mode config added. Major revamp based on SK config.
* * Spell set is currently aimed at 100+ and likely will not work well at lower levels.
* * This config does not contain a DPS mode.
* * Feedback is desired on specific options and gem selections.
[WAR]
* Beta config added. Near total rewrite.
* * Rearranged and added new rotations and ability entries.
* * * Rotations and defensive action cycling is based on a 10-minute, automation-sustainable, group-play based model.
* * * Added emergency rotations that SHD …
=> Class config additions

class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live/dru_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/dru_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
[SHM]
[DRU]
* Added a toggle setting for Group Regen buff due to cross-stacking with certain lower-level spells.
=> Fix Group Regen buff spam

class_configs/Live - Experimental/clr_class_config.lua, class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live - Experimental/nec_class_config.lua, class_configs/Live/ber_class_config.lua, class_configs/Live/brd_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/clr_class_config.lua, class_configs/Live/dru_class_config.lua, class_configs/Live/mag_class_config.lua, class_configs/Live/mnk_class_config.lua, class_configs/Live/nec_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/ber_class_config.lua, class_configs/Project Lazarus/brd_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/clr_class_config.lua, class_configs/Project Lazarus/dru_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/mnk_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, doc/Default_Config_FAQ.html, modules/movement.lua, utils/casting.lua, utils/config.lua
* Fixed a typo in the Med Delay setting name (this will require re-adjusting any values change from default, unfortunately).
* Changed the Feigning function to be IAmFeigning to avoid potential confusion.
=> Post utils-refactor minor changes

class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live/dru_class_config.lua, class_configs/Project Lazarus/dru_class_config.lua
* Removed detrimental or erroneous entries.
* Note: further adjustment and AA additions will occur at a later date.
=> [DRU] Clean up MoveSpell line

class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, utils/casting.lua
[casting]
* Renamed "IsDisc" to "IsActiveDisc" and adjusted duration check to prevent undesired /stopdisc commands.
[WAR]
* Corrected entries in the Defenses rotation.
=> Active Disc check improvements

class_configs/Live - Experimental/clr_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
* Some configs that were ported from private configs didn't have this code updated
=> Pointed older group buff target checks to newer helper function

utils/ui.lua
=> Fix for crash when clicking named on named list

class_configs/Live - Experimental/clr_class_config.lua, class_configs/Live/ber_class_config.lua, class_configs/Live/clr_class_config.lua, class_configs/Live/nec_class_config.lua, class_configs/Live/pal_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/ber_class_config.lua, class_configs/Project Lazarus/clr_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua, class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/war_class_config.lua
* When underwater, battle leap launches us above the surface, regardless of our current depth. Updated warrior checks to also use HeadWet member (as opposed to FeetWet).
* Also corrected a few typos/extraneous comments.
=> Added rocket launch prevention code to BER battle leap.

doc/Commands_FAQ.html, init.lua, modules/movement.lua, utils/config.lua
* Removed trace information from splash message
* Reduced message length and repetition for settings change
* * Added nil safety and small bugfixes to these functions
* Removed go2ggh command
=> Message formatting improvements

utils/combat.lua, utils/event_handlers.lua, utils/item_manager.lua, utils/targeting.lua
* Added third dimension to certain target distance checks
* Tightened some percentages to pull the PC in closer when repositioning due to "too far" or "can't see" issues.
* Added "uw" flag to some stick commands
=> Engage and navigation improvements

modules/class.lua, utils/classloader.lua
* Errors in the underlying function have been corrected.
=> Re-enabled "Create Custom Config" button.

utils/binds.lua
=> Fixed task select window error in "/rgl yes" command

utils/casting.lua
*Most spells will now cancel casting when the target's range moderately exceeds the spell range (>20%).
* * We are looking at you, 8-second-cast-buff-when-my-tank-already-ran-off.
=> Added range-based stop cast (Thanks robbanEQ!).

init.lua, modules/charm.lua, modules/drag.lua, modules/faq.lua, modules/mez.lua, modules/movement.lua, modules/named.lua, modules/performance.lua, modules/pull.lua, modules/travel.lua, utils/config.lua
* Properly hid pop settings
* Corrected typos
=> Post-UI Update Cleanup

modules/pull.lua
* Added "Ammo" to valid ranged weapon types for pull abilities.
=> "Ranged" Pull Ability Fix (Thanks Daneki!)

class_configs/Project Lazarus/enc_class_config.lua, modules/mez.lua
* Changed setting name to avoid boolean/number miscompare
* Fixed Laz config entries
=> Fix for Twincast Mez

class_configs/Live/enc_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua
* Minor condition fix in live config
=> [ENC] Remove some entries/settings not present on Laz

class_configs/Project Lazarus/enc_class_config.lua
=> [ENC] Added support for Laz-specific auras (Thanks RobbanEQ!)

class_configs/Live - Experimental/pal_class_config.lua, class_configs/Live/pal_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/war_class_config.lua
[PAL] Added the Marr's Salvation group hatred reduction buff (optional, default: false).
[WAR] Refactor AE Damage check to better leverage SpawnCount.
=> Minor Tank Updates

modules/pull.lua
* Added the option to hold pulls if a group member corpse is detected (Default: true).
* If the above is enabled, added an option to hold pulls for a time period after a corpse is no longer detected, to allow for rebuffs (Default: 0, Max: 90).
* * Please note that this is imperfect: battle rezzes won't be detected, and group buff rotation timers will still apply. Further optimization possible but unlikely (refactor would be onerous).
* resolves #368
=> Pull Module Improvements

class_configs/Project Lazarus/bst_class_config.lua
added missing mana-regen BST spell
=> Fix Spell regen BST Lazarus

class_configs/Project Lazarus/enc_class_config.lua
Namechange on the AA for slow on Lazarus
=> Fix Ench AA Slow Lazarus

class_configs/Project Lazarus/shm_class_config.lua
=> Fix Shaman AA malo and slow Lazarus

class_configs/Live/mag_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua
Changed name and lvl on AA to work on Lazarus
=> Fix AA malo Lazarus

lib/lootnscoot/loot_lib.lua, modules/loot.lua
Added Pop up window option for new items.
Added Links to the loot tables. (these will populate for items missing them as you loot items) Added Toggle to only loot a corpse once.
The new items pop up allows you to set items rules yourself for items not already in the table. The fields will be prefilled with your evaluated settings.
If the item was not no drop then we will make the decision and loot accordingly, and show the window.
If you have only loot corpse on and a new item appears, saving the settings from the new item popup will unflag that corpse incase there was a nodrop item on the corpse and we wanted to loot it.
Window includes  the following information:
* Link button,
* Item Name,
* Nodrop,
* Lore,
* Augment,
* TS,
* Sell Price.
=> Loot Updates

class_configs/Live/enc_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua
added spellproc to gem 3 if we have the tash AA
fix AA slow name in slot 4
=> Update enc_class_config.lua Lazarus

class_configs/Live - Experimental/wiz_class_config.lua, utils/casting.lua
* Damage is now more gooder than before with some pretty okayish rotation flow improvements.
* * Added some burn things to make some things burn more
* * Added a fullrotation flag for the DPS rotation and stopped Vortex from casting on things with very low health.
* Condensed and adjusted aggro management and combat buffs.
* Laid internal groundwork (clearing/identifying spell slots) for eventual AE dps additions.
* Made a small adjustment to Casting.TargetedSpellReady() to ignore movement checks if the cast is instant.
=> [WIZ] Experimental Config Updates

class_configs/Live - Experimental/wiz_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua
* [BST, ENC] Fixes and improvements to slow entry/rotation checks for all configs.
* [WIZ] Additional minor adjustments to Experimental config.
=> Config Updates

modules/pull.lua
* Removed reliance on cached buffs from the buff count feature.
=> Pull Module: Buff Count Fix

class_configs/Live/bst_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua
Added missing AA's
removed roundkick
fixed error in name
=> Update bst_class_config.lua Lazarus

class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live - Experimental/nec_class_config.lua, class_configs/Live - Experimental/pal_class_config.lua, class_configs/Live/brd_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
Please note further updates of this nature are planned.
* (Live Configs)
* * Added support for Blood/Spirit Drinker's Coating for the following classes: SHD, BST, BRD, PAL (exp.)
* [BST] (Live/Laz)
* * Added support for OoW Chests.
* * Added AE count and safety checks.
* * Added AE Roar options/entries.
* * Added Vet AA options/entries.
* [SHM] (Live/Laz)
* * Added options for Epic use (off/burn/all combat).
=> Class Feature Homogenization Pass

class_configs/Live - Experimental/nec_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/mag_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
* Added Aegis and Fortify pet buffs where appropriate.
* * If I missed one here, let me know!
* Removed Companion's Aegis (which isn't present on Laz).
* Tightened condition check for Pet Buff AA.
=> Laz Pet Buffs (Thanks sputnik!)

utils/casting.lua, utils/config.lua
Adjusted the conditions under which we will attempt a retry on spell casts.
=> Spell Cast update

class_configs/Live - Experimental/nec_class_config.lua, class_configs/Live/nec_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua, modules/class.lua, modules/movement.lua, modules/pull.lua, utils/binds.lua
* Reduced the number of rotation checks for out-of-combat rotations which did not already have a rotation timer (before: Gatling Gun, now: Every second).
* Command usage and information pass for clarity and uniformity.
=> Adjustments

lib/lootnscoot/init.lua, lib/lootnscoot/loot_hist.lua
=> fix: report not toggling

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, utils/ui.lua
* Fix for incorrect conditions for Gem 7.
=> Cleric Beta Fix

class_configs/Live - Experimental/pal_class_config.lua, modules/class.lua
* Fixed a crash involving persona changing and drawn combo boxes.
* [PAL] (Expir) Fixed a couple of option categories.
=> Lazy Sunday

class_configs/Beta/mnk_class_config.lua, class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live - Experimental/pal_class_config.lua, class_configs/Live/brd_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Live/mag_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/brd_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, modules/class.lua
Rotations now support load conditions to control whether they are loaded. Custom config users: Feature is 100% optional and backwards compatible. Please refer to the forum post for more information, instructions, and examples.
https://www.redguides.com/community/threads/introducing-rotation-load-conditions.93764/#post-640221
=> Rotation Load Conditions

class_configs/Beta/mnk_class_config.lua, class_configs/Beta/rog_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/mag_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/war_class_config.lua
=> Minor Updates

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, class_configs/Live/clr_class_config.lua, class_configs/Project Lazarus/clr_class_config.lua, utils/core.lua
Speculative fix for attempting to use AE rez out of turn.
=> Cleric Rez Function

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, modules/pull.lua
Update for 2/7 Laz Patch (PAL/SHD)
Additional changes:
* Added logging to Pull/Combat timer for debug purposes.
* Updated some Cleric (Beta) FAQ entries.
=> Laz Updates

class_configs/Live - Experimental/wiz_class_config.lua, utils/event_handlers.lua
* Added support for AE Damage:
* * Added the "Beam" line of spells (Frontal AE), with a specific toggle option and target count.
* * Added the "of Flame" line of spells (PBAE), with a specific toggle option and target count.
* * The "Do AE Damage" and "Max AE Target" govern all AE spells and can be used to quickly adjust behavior without changing spell gems.
=> WIZ (Live - Experimental) Updates

class_configs/Live/ber_class_config.lua, class_configs/Project Lazarus/ber_class_config.lua
* Do Intimidate now defaults to false.
=> BER Update (Thanks pingkiller!)

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, modules/loot.lua
Fix for crash on config change.
=> Loot Module Update

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
* Standardized any usage of the above to "Dot" (in any table or function, left comments and tooltips alone).
* Updated Stun entry on Cleric Beta.
=> Dot dot DoT more DOTS

class_configs/Beta/mnk_class_config.lua
* Added FD ability to emergency rotation
=> MNK Beta Update (Thanks pingkiller!)

class_configs/Live/shd_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, modules/pull.lua, utils/binds.lua
* Fix for Pull Delay not being respected after combat. Fixes #439
* Added "/rgl say" command: As "/rgl qsay", without the random delay.
* Added LifeTap2 to SHD pull abilities, fixed the LifeTap pull entry.
=> Pull Fix, New Command, SHD pull fix

class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Live/mag_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua
Minor upates to class configs during Laz group leveling
=> Minor Tweaks

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua
* Fleshed out stun options and FAQs
=> Beta Cleric Update

lib/lootnscoot/init.lua, lib/lootnscoot/loot_hist.lua
some tweaks, fixes, and new stuff.
Added Loot History table.  so you can search or look up items you have already looted, search by zone item date etc.
fixed new items table ordering.
Cleaned up settings window
fixed duplicating settings. 
Fixed window scrolling
you can adjust the size you want scrolling to start at by dragging the inner border up or down from the bottom
=> loot stuff

class_configs/Live - Experimental/wiz_class_config.lua
[WIZ-Experimental]
* Added support for 1-70 with an option for choice of element. (Default: Fire)
* Added support for stuns, snares, etc.
* AE support for low level is WIP currently:
* * PBAE will be added.
* * Rains are TBD (may be added, pending more research).
* * * Please note the existing default config should support Rains if you must have them.
This config is being actively developed and will transition to beta once all level ranges are supported.
=> Low Level additions for Wizard (Exper)

class_configs/Live - Experimental/wiz_class_config.lua
[WIZ - Exper] Added some omitted settings.
=> Follow-on WIZ Update

class_configs/Live/mag_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua
=> Mage fixes (Thanks KC/RYN!)

class_configs/Live - Experimental/dru_class_config.lua, class_configs/Live/brd_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/dru_class_config.lua, class_configs/Live/mag_class_config.lua, class_configs/Live/nec_class_config.lua, class_configs/Project Lazarus/brd_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/dru_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua
Debuffs from numerous classes should now respect the Debuff Min Color setting.
=> Debuff Update

class_configs/Live/mag_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua
* [MAG-All] Corrected element use for low level rotation.
* [SHD-Laz] Added a check for a popular outside buff to Call Attack buffs to correct improper stacking information supplied to the script.
=> MAG/SHD Fixes

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, modules/class.lua
* Re-added Divine Intervention toggle.
* Re-ordered gems and fallbacks.
=> Cleric (Beta) Update

class_configs/Live - Experimental/wiz_class_config.lua
* Added initial support for the 70-100 level range.
* Initial support for Low-Level (53-70) PBAE Mode.
* * Aimed at Laz, where it is used in AE AA farming; may be relevant on other emu servers.
* * Utilizes the three "Jyll" spells and the timer 4 PBAE.
* * Falls back on your chosen element when target count is low.
To-do: Adding alpha support for 100-110ish (RoK era). Right now we will use the 110+ aimed rotations from 100+.
=> WIZ (Experimental) Update

class_configs/Project Lazarus/mag_class_config.lua
* Changed Fire Orb summon to trigger autoinventory for the entire group (this is a group-wide summon on Laz).
=> MAG (Laz) Update

class_configs/Live - Experimental/wiz_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua
* Adjusted select AE Damage settings and tooltips for clarity.
* Ensured uniformity for the relationship between AE settings and gem selection.
=> AE Damage Update

class_configs/Cleric Beta - Live/clr_class_config.lua, class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua, class_configs/Live/pal_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, modules/loot.lua
[SHD]
* AC and Attack Taps are now separate entries with their own options.
* Added entries for hate buff spells.
* Slightly reordered AE ability options and gems.
* Added Unbridled Strike of Fear AA to Laz configs (Thanks sputnik!).
* [PAL] Edited entries for Bash in default configs.
* [CLR-Beta] Added Laz rez spell to Laz config.
=> Class Config Updates

utils/event_handlers.lua
* Moved "Too Far" and "Can't See" messages to the debug channel.
=> Event Handlers

class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
* [SHM] Expanded shrink options to include single-target spell and AA.
=> Small Update

utils/casting.lua
* Adjusted buff stacking checks to account for "Unknown" trigger spells with an ID of 0.
=> Stacking Checks

lib/lootnscoot/init.lua
fix: bulk set and group commands
=> fix: bulk set and group commands

class_configs/Alpha (Live)/dru_class_config.lua, class_configs/Alpha (Live)/nec_class_config.lua, class_configs/Alpha (Live)/pal_class_config.lua, class_configs/Alpha (Live)/wiz_class_config.lua, class_configs/Alpha (Project Lazarus)/dru_class_config.lua
* "Experimental" configs are now renamed to "Alpha" (Pardon the orphaned files).
* Split off Druid Alpha (Live) to create a Laz-specific config.
Information on Alpha/Beta configs can be found in the stickied post on the RG forums.
=> Alpha Config Update

lib/lootnscoot/init.lua
added checkboxes to rules tables for bulk setting.
nodrop items being looted when disabled should be fixed.
=> nodrop fix, bulk rules checkboxes

class_configs/Live/rng_class_config.lua, class_configs/Project Lazarus/rng_class_config.lua
* Removed duplicate "Riftwind's Protection" entry.
=> Ranger Update

class_configs/Live/enc_class_config.lua
* Fixed setting typo on Live config.
=> Enchanter Update

utils/casting.lua
* While casting, we will now ensure our pets are attacking the things, if the things need attacked.
=> Pet Update (thanks pingkiller!)

lib/lootnscoot/init.lua, lib/lootnscoot/loot_hist.lua
feat: `/lns buy` commands
`/lns buy` -- set item on cursor to buy, qty 1
`lns buy #` -- set item on cursor to buy, qty #
`/lns buy "Item Name" `-- set item name to buy qty 1
`/lns buy "Item Name" #` set item name to buy qty #
=> cosmetics, cli options

modules/loot.lua
fixes the first load crash issue from the loot module.
=> fix: loot module crash

utils/casting.lua
* Fix for invalid characters being passed in DanNet buff checks.
=> PeerBuffCheck Fix

class_configs/Alpha (Live)/pal_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, utils/casting.lua
See individual commit messages
=> Casting and Config Fixes

modules/pull.lua, utils/casting.lua, utils/combat.lua
=> Autotargetfix

class_configs/Alpha (Project Lazarus)/dru_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua
* [DRU] Handling for improper stacking report on Spirit of the Black Wolf.
* [SHD] Added support for Third Spire.
(Note: Additional spire support and selection options are planned for all classes; recent additions are stopgaps).
=> Minor Laz Updates

lib/lootnscoot/init.lua
cleaned up the reporting for selling and added buying to the report.
Should now show Plat Gained, Plat Spent, and Total Profit.
added quest keep qty option to bulk settings.
=> sell\buy reporting and bulk quest qty

class_configs/Live/brd_class_config.lua, class_configs/Live/rng_class_config.lua, class_configs/Project Lazarus/brd_class_config.lua, class_configs/Project Lazarus/rng_class_config.lua
* [BRD] Added missing "Cassindra's Chorus of Clarity".
* [RNG] The Move Spell entry will now respect its setting.
=> Config Updates (Thanks Redfrog!)

utils/casting.lua
Corrected a condition under which buff checks would not use the proper rank of a discipline.
=> Buff Check Update

lib/lootnscoot/init.lua
this started ignoring the qty and just kept looting.
Smacked that function around a bit and it behaves again.
=> fix: qty checks

init.lua, modules/pull.lua, utils/config.lua
persistance
added toggle for pause\resume and pull start\stop
added commands `/rgl startpull` and `/rgl stoppull`
these commands will start and stop pulling for the character that ran them using your currently set mode
=> Mini Btn Updates

modules/class.lua
* Cure checks now query for mesmerization.
* Removed the specific counter check from Live (as we already bypassed this on emu).
=> Cure Update

utils/casting.lua
Fix for invalid pet buff check.
=> PetBuff Fix (Thanks sputnik!)

class_configs/Project Lazarus/shd_class_config.lua
Partial revamp of rotations to better account for the differences between the Live/Emu and Laz Environments.
* Adjusted conditions and settings for defensive and emergency rotation and ability use.
* Added conditions to the Hate Tools rotation and moved AE Hate Tools into their own rotation.
* Rolled the weave rotation into the Combat rotation due to small number of entries.
* We will be a little more selective in when we use Epics or OoW chests.
=> SHD (Laz) Major Update

init.lua, utils/casting.lua
* Lowered the aggro threshold to bypass combat medding to 70%.
* Removed MQ2 rez setting changes.
=> Settings Update

class_configs/Project Lazarus/wiz_class_config.lua, utils/casting.lua
* Corrected issues with Improved Familiar/Familiar spell checks.
* * Further support is planned for Laz-specific familiars.
* Adjusted item use cast checks to account for very short cast times that aren't always captured clientside.
=> WIZ (Laz) Fix, Item Use Fix

class_configs/Live/shd_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua
* Added the missing level 64 pet buff, "Augmentation of Death".
* Corrected an error in buff reporting for the Pet Buff spell line.
=> SK Update (Thanks tarb!)

class_configs/Project Lazarus/wiz_class_config.lua
* Added support for AA familiars.
* * Used a single entry to return the best familiar the Wizard can use from the following: Kera's, Ro's, Improved.
=> Wiz (Laz) Familiars

class_configs/Project Lazarus/wiz_class_config.lua
=> Wizard (Laz) Burn

class_configs/Beta (Live)/wiz_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/wiz_class_config.lua, utils/targeting.lua
* Added a helper function to assist with checking PBAE range checks.
* * Added check to entries in PBAE Rotations: WIZ (Laz, Live Beta), MAG (Laz).
=> PBAE Update

class_configs/Alpha (Live)/dru_class_config.lua, class_configs/Alpha (Project Lazarus)/dru_class_config.lua, class_configs/Project Lazarus/wiz_class_config.lua
* [DRU - Alpha]
* * Added custom laz groupheals.
* * Corrected TwinHealNuke entry (description innacurate, nuke is targeted, not ToT).
* [WIZ] Added Arcanum Weaves.
=> Laz Config Updates

class_configs/Live/enc_class_config.lua
* Corrected an improper check in the twincast aura entry (Thanks Tstone!)
* Refactored and expanded aura handling. We will detect and remove an undesired aura dynamically, based off of currently selected options, available spell lines, and whether you have purchased Auroria Mastery or not.
* As a recap, here is the current default config's aura logic:
* * * The XP Bonus (Learner's) aura will be used if the option is selected.
* * * The twincast aura will be prioritized in all other situations.
* * * The spell proc (Mana) aura will be used whenever an aura slot is available and the above two conditions are satisfied.
* * * Any other desired outcomes or combinations should be addressed with a custom config file, thank you!
=> ENC(Live) Update

class_configs/Live/rog_class_config.lua, class_configs/Project Lazarus/rog_class_config.lua
* Corrected the sneaking check while chase is enabled.
=> Rogue Update (Thanks Robban!)

class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
Refactor for previously added effect types to the cure checks.
* Fix for #582
=> SHM Cure Update

class_configs/Beta (Project Lazarus)/dru_class_config.lua
Minor adjustment to allow rains to be used at lower mob health.
=> Druid(Laz - Beta) Update

utils/casting.lua
* Adjusted cast time thresholds to prevent missing a callback when a cast is too fast for the client to show a cast window (100ms cast time laz clickies).
=> UseItem Update (Thanks sputnik!)

modules/mez.lua
Overall improvement of logic and mez usage, with the primary focus of correcting the issues with bypassing an AE mez in favor of repeated single mezzes, especially when mobs continued to add to the encounter.
* Pushed some checks up and down in the loop as necessary.
* Removed some duplicate checks.
* Added a fallback check for AE mezzing in the mez list
* Allowed the Mez List to properly populate and be utilized when single-target mezzing was disabled.
=> Mez Module Update

class_configs/Live/bst_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/war_class_config.lua
* [BST] Corrected Pethealspell setting name.
* [WAR] Corrected stand disc checks.
=> Minor Config Fixes

class_configs/Live/bst_class_config.lua, class_configs/Project Lazarus/war_class_config.lua
Correct file not included in commit
=> Follow-on to #599

class_configs/Project Lazarus/dru_class_config.lua, utils/casting.lua
* Adjusted OkayToRez to account for corpse being rezzed mid-check.
* Added additional debug messaging.
* Corrected possible spam condition (thanks sputnik!)
=> Emu Rez Adjustments

class_configs/Project Lazarus/dru_class_config.lua, utils/config.lua
* Cheetah will now respect the movement buff option.
* Added support for electing not to use a spire.
=> DRU (Laz - Beta) Update

class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua
* Corrected MAG/NEC pet burn AA names.
=> Laz Pet Burn AA (Thanks sputnik!)

class_configs/Project Lazarus/shd_class_config.lua
Visage of Death now has a toggle, which can be found on the Buffs/Debuffs tab of the Class options.
=> SHD - Laz Update

class_configs/Alpha (Live)/pal_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, modules/debug.lua
* Refactored helper functions in tank class configs to only count unique ID's from the XTarget window.
* Added Sets to the Debug pre-loaded module list.
=> Follow-up to XTHater changes

class_configs/Alpha (Live)/pal_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/war_class_config.lua
=> DefensiveDiscFix

utils/targeting.lua
Fix for rare crash occurrence when checking facing.
=> Facing Check Fix (Thanks mackal!)

class_configs/Project Lazarus/mag_class_config.lua
* Added Epic use to burn rotation (previously only found in Pet Buffs).
=> Magician - Laz

class_configs/Project Lazarus/dru_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua
* Added various clicky items (DRU/ENC/SHD/SHM).
=> Laz Configs

class_configs/Project Lazarus/clr_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua
* [SHD] Altered defense rotations to account for Laz Omens chest customization.
* [ENC] Added HC swarm clicky.
* [CLR] Added Tacvi Hammer.
* * Slightly reordered big heal rotation.
=> Laz Config Adjustments

class_configs/Live/mag_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua
Certain DPS rotation abilities should no longer be disabled if Pet Tank mode is active.
=> MAG Adjustments

class_configs/Live/enc_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua
Corrected Dispel rotation to properly check for a beneficial effect on the target.
=> ENC Update

class_configs/Live/rog_class_config.lua, class_configs/Project Lazarus/rog_class_config.lua, utils/casting.lua, utils/combat.lua, utils/targeting.lua
[ROG]
* Added Aggro Management rotation.
* * Added entry for Hide.
* * Moved Escape from emergency rotation.
* Corrected pre-engage checks.
Pre-Engage
* Adjusted the combat routine slightly to better support variances in BER/RNG/ROG pre-engage functions.
=> Rogue and Pre-Engage Adjustments

class_configs/Project Lazarus/enc_class_config.lua
Moved Eldritch Rune/Veil of Mindshadow entries to better reflect their usage on Laz.
=> ENC(Laz) Update

modules/class.lua, utils/binds.lua
* Added /rgl rsay, which expands /rgl say functionality to include the entire raid.
* Fix for corpse name for in-group zone check.
=> rsay command

modules/clickies.lua, utils/casting.lua
* Fixed a condition in which certain clickies were incorrectly reporting cast time.
* Refactored use code to call existing helper functions.
=> Clicky Update

utils/config.lua
Corrected typo and improved tooltip/FAQ entry for new Rez settings.
=> Rez Update

class_configs/Project Lazarus/brd_class_config.lua, doc/BRD_Class_FAQ.html
* Added support for custom Lazarus spells.
* Retooled rotations
* Removed legacy bard song selection code in favor of newer priority spell list.
* Restructured options
While playtesting was not as extensive with this config as I would like, the lack of any support for custom spells makes it worthwhile to push immediately.
=> Bard(Laz) Revamp

utils/casting.lua
* Added a delay before we will evaluate song cancellation to prevent the server from resuming the cast.
* A special thank you to mackal, guest01, and Coldblooded for their assistance in reporting, troubleshooting and solving this issue!
=> UseSong Update

class_configs/Live/clr_class_config.lua, class_configs/Project Lazarus/clr_class_config.lua, utils/ui.lua
Can't cast Yaulp while mounted so don't.
=> Don't cast Yaulp while mounted

class_configs/Live/clr_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Project Lazarus/brd_class_config.lua, class_configs/Project Lazarus/clr_class_config.lua, modules/clickies.lua, modules/debug.lua
* [CLR-All] Added Bash. (Thanks RYN227!)
* [ENC-Live] Corrected SpellShield/Auspice not respecting settings. (Thanks guest01!)
* [BRD-Laz] Corrected Shout setting. (Thanks Laz Event Yesterday!)
* Lowered default Combat Clicky delay to 5s (old value: 10s).
* Cleaned up duplicate code in debug module.
=> Various Adjustments

class_configs/Live/ber_class_config.lua, class_configs/Project Lazarus/ber_class_config.lua, utils/casting.lua
* Adjusted range checks during casting if we are the target.
* [BER] Added valid ranges to axe summoning functions.
=> Casting Update

class_configs/Alpha (Live)/dru_class_config.lua, class_configs/Live/dru_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/dru_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua, modules/class.lua
* Corrected a potential spam condition for the Call of the Wild AA.
=> Call of the Wild Update (Thanks guest01!)

modules/mez.lua
* Refactored Mez code to wait for a reasonable time period if we are currently casting, moving, or in the global cooldown.
* ENC: while AE mezzing, Beam of Slumber should only fire if we are in the global cooldown or if the AE mez spell gem timer is not ready.
* BRD: if we are ST mezzing, we will always attempt to use Dirge of the Sleepwalker before we waste time on a song.
* Allowed AE Mez to continue when the target dies.
* Reduced retry attempts on all mezzes.
* Ensured we turned attack off when updating the mez list.
* Added another failsafe to switch to AE mez while under certain conditions while we are waiting for ST mez to be ready.
* Added an additional autotarget ID check before we perform a single target mez.
* * Known Issue/Limitation: During mez processing, we do not update …
=> Substantial Mez Update

class_configs/Project Lazarus/dru_class_config.lua
* Added options for when to use Epic 1.5/2.0 (ported from BRD/SHM).
=> Dru (Laz) Update

utils/config.lua
* Autotarget settings are now hidden by default (and exposed with the advanced settings toggle).
=> Config Update

class_configs/Alpha (Live)/nec_class_config.lua
* Added (optional) support for combat pet resummon.
* * Further improvements are planned (eventually).
* Converted to new spell lists for ease of future adjustment.
=> NEC (Live-Alpha) Update

class_configs/Live/bst_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, modules/mez.lua
* Fixed a couple of potentially improper GemTimer checks.
* Fixed a range check for MAG(Laz).
=> Bug Squashing

.vscode/settings.json, modules/pull.lua
* Fixed a situation in which Marr's or GM Buffs would be detected as debuffs.
=> Laz Pull Fix (Thanks Klunk!)

class_configs/Alpha (Live)/pal_class_config.lua, class_configs/Beta (Project Lazarus)/pal_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, utils/targeting.lua
* Revamped Paladin config and aligned it to other tank configs.
* Added helper functions and made minor adjustments to all tank config aggro management.
* Added helper functions for certain stun checks.
=> PAL(Laz) Beta 2.0, Aggro and Stun Updates

class_configs/Beta (Project Lazarus)/pal_class_config.lua
* Removed Undead Debuff rotation (AA not available on Laz).
* We will no longer attempt to use Marr's Salvation on tanks.
=> PAL(Laz-Beta) Updates

modules/pull.lua
* Added a temporary pull ignore list:
* * Any (automatic) attempt to pull a target for more than (Ignore Timer setting) will add it to an ignored list.
* * Directed pulls using the "Pull Target" button will not trigger this check.
* * The ignored list will be cleared when you turn off pulling, zone, use the button in the pull UI, or issue the /rgl pullignoreclear command.
Feedback is requested on functionality and potential improvements.
=> Pull Enhancements

class_configs/Live/clr_class_config.lua
Removed certain unused trigger spells from AC Buff and Spell Haste list. (Thanks scvone and mackal!)
=> CLR(Live) Spell Fix

class_configs/Beta (Project Lazarus)/pal_class_config.lua
* Added Sanctification Disciple entry.
=> PAL(Laz-Beta) Update

class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua
* Adjusted some checks on BST and MAG to manually handle incorrectly reported buff stacking.
=> Laz Buff Deconflicts

class_configs/Alpha (Live)/dru_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Project Lazarus/mag_class_config.lua, class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/wiz_class_config.lua
Live
* [DRU, SHM] - Fix for TwinHeal check.
Laz
* [MAG]
* * Added support for Frantic Flames on burns.
* * Added seb fungi entry.
* * Expanded pet healing options.
* [PAL]
* * Added seb helm/hands
* * Added option for Serene Stun.
=> Config Adjustments

class_configs/Project Lazarus/nec_class_config.lua
Overhauled the default Necromancer config for Project Lazarus.
* All facets of this config have been adjusted, and numerous options have been added. Please allow a moment to familiarize yourself with the changes on your next login.
* Feedback is welcome for the journey *to* 70, as this is a particularly difficult class to conform to a default.
* Please note that many of the endgame Laz clickies may need to be worked in over time, but I have (hopefully) constructed rotations in a manner will be conducive to adding them.
=> NEC(Laz) 2.0 release

class_configs/Project Lazarus/pal_class_config.lua, init.lua, utils/config.lua
[PAL-Laz]
* Added "GroupedWithTarget" checks to wave heals used outside of the group heal rotation.
[General]
* Added instance check for resiliency.
=> PAL(Laz), Zoning Updates

class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua, utils/casting.lua
* Improved support for target buff checks when more than one DoT effect is present.
* Added helper function for DoTs from items.
* Realigned some dot entries on NEC(Laz) to use the above.
=> Dot Adjustments

class_configs/Project Lazarus/pal_class_config.lua
* Added "Okay to Not Heal" conditions to certain offensive rotations.
* Slightly adjusted rotation position for PBAEStun for tank mode.
=> PAL(Laz) Update

class_configs/Live/rng_class_config.lua, class_configs/Project Lazarus/rng_class_config.lua, utils/combat.lua, utils/event_handlers.lua
* Rewrote Ranger config from scratch for Project Lazarus. All facets of this config have drastically changed. 
Ranger Combat Nav (Live, Laz):
* Refactored for resiliency in some edge cases. 
* Added better debugging text and a warning to the user when can't see messages conflict with reported line of sight.
=> RNG(Laz) 2.0, Ranger Combat Nav Update

class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/rog_class_config.lua
Rogue config is now baselined for Project Lazarus.
* Other than disc/map cleanup, only minor adjustment was required.
=> ROG(Laz) Update

class_configs/Live/pal_class_config.lua
* Adjusted Holyforge entry and added Pureforge to burn.
=> PAL(Live) Update (Thanks Fargrim!)

class_configs/Live/shm_class_config.lua
Retrofit the default config with features that have been developed since it was published:
* Added load conditions to add or remove entries from rotations dynamically based on our current settings.
* Refactored spell selection to use priority-based spell lists. At the default settings, the spell loadouts for Hybrid and Heal modes on live should remain unchanged, however, the order may be slightly different than before. Granularity in choosing those gems has been improved:
* * Added individual toggle settings for some DPS abilities.
* * Added extra settings and logic for memorizing cure spells.
* * The Heal DPS setting is now a top-level toggle that can quickly be used to cut DPS abilities in heal mode without changing spell loadout.
=> SHM(Live) Update

class_configs/Project Lazarus/ber_class_config.lua, class_configs/Project Lazarus/mnk_class_config.lua, class_configs/Project Lazarus/rog_class_config.lua, class_configs/Project Lazarus/war_class_config.lua
* Monk config is now baselined for Project Lazarus.
* * Other than disc/map cleanup, only minor adjustment was required.
* Adjusted Third Wind usage for melee class on Lazarus. Disabled Second Wind for non-warriors by default.
=> MNK(Laz) Update, Endurance Disc Update

ui/standard.lua, utils/ui.lua
* Adjusted assist list buttons to use the same line.
=> Assist List UI

modules/pull.lua
Added fallback checks to stop certain swarm and temporary pets from possibly becoming a pull target.
* Shoutout to grimmier for the initial legwork/homework on this.
=> (Emu) Pull Update

class_configs/Project Lazarus/shm_class_config.lua
Fix for epic 1.0 spam under certain conditions.
=> SHM(Laz) Epic Fix

class_configs/Alpha (Live)/dru_class_config.lua, class_configs/Live/brd_class_config.lua, class_configs/Live/bst_class_config.lua, class_configs/Live/clr_class_config.lua, class_configs/Live/dru_class_config.lua, class_configs/Live/enc_class_config.lua, class_configs/Live/nec_class_config.lua, class_configs/Live/rng_class_config.lua, class_configs/Live/shd_class_config.lua, class_configs/Live/shm_class_config.lua, class_configs/Live/war_class_config.lua, class_configs/Live/wiz_class_config.lua, class_configs/Project Lazarus/ber_class_config.lua, class_configs/Project Lazarus/brd_class_config.lua, class_configs/Project Lazarus/bst_class_config.lua, class_configs/Project Lazarus/clr_class_config.lua, class_configs/Project Lazarus/dru_class_config.lua, class_configs/Project Lazarus/enc_class_config.lua, class_configs/Project Lazarus/nec_class_config.lua, class_configs/Project Lazarus/pal_class_config.lua, class_configs/Project Lazarus/rng_class_config.lua, class_configs/Project Lazarus/shd_class_config.lua, class_configs/Project Lazarus/shm_class_config.lua, class_configs/Project Lazarus/war_class_config.lua, class_configs/Project Lazarus/wiz_class_config.lua
Linked previously added functions improving immunity detection to all appropriate default class configs.
=> Slow/Stun/Snare Immunity Update

class_configs/Project Lazarus/clr_class_config.lua, modules/clickies.lua, utils/config.lua
* Added logic block to use clickies based on a particular itemcount range.
* Fixed a couple of miscategorized settings.
=> Clicky Item Count condition

modules/faq.lua, modules/loot.lua, modules/movement.lua, ui/options.lua
* Tooltip/FAQ pass of Movement and Loot Modules.
* Minor UI adjustments.
=> UX Update 2 : Movement, Loot

utils/classloader.lua
Custom Configs are now created in server or environment-specific folders in the rgmercs folder in the MQ config directory.
* Official servers will find their custom configs in class_configs/Live.
* Emu servers will find their custom configs in class_configs/ServerName.
* Sunsetted support for custom configs in the base directory (this was deprecated nearly a year ago).
=> Custom Config Update
