DerpleMQ2/rgmercs

- utils/rgmercs_utils.lua
Allows for complex loadout organization taking into account user-selected UI options.  Intended primarily for bards.
To use, set `_ClassConfig['Spells'] = { getSpellCallback = <callback fn> }` in place of the concrete list.  
If getSpellCallback does not exist, we use prior default behavior.
> Add optional callback "getSpellCallback()" to class config spell loadouts

- utils/rgmercs_utils.lua
Name() alone fails on 125 at least, probably earlier than that, too.
> Fix Utils.SongMemed to use TLO Spell.RankName() in addition to plain Name()

- class_configs/bst_class_config.lua
Added RankName() call to the retrieved userdata from ResolvedActionMap, Bst was otherwise spewing errors
> Fix bst config treating userdata as string in helper functions

- class_configs/enc_class_config.lua
- class_configs/nec_class_config.lua
[ENC]
- Chest click added to (bottom of) Burn rotation, DoChestClick added to options (default: true).
- Insanity can now be "Calculated" rather than "Alculated".
[NEC]
- Added OoW Chests to Item List and (top of) Burn rotation.
> Minor ENC/NEC updates

- modules/pull.lua
the assignment was backward when checking the state. instead of assigning the resourceStartPct  (aka the resume value) it was assigning the resourceSopPct (aka the pause pulls value)
could have either flipped the assignments or just switched from == to ~=
also added in a WARN debug message.
> groupwatch wasn't resuming at the correct percentage

- class_configs/bst_class_config.lua
- class_configs/enc_class_config.lua
- utils/rgmercs_utils.lua
[BST] Corrected typo in Focused Paragon
[Utils] Slightly modified the underlying function behind the Paragon rotation so Paragon and Focused Paragon weren't used if the BST had 100% mana.
[BST] Adjusted rotations so that (group) Paragon of Spirit would properly fire only when a group member was under the ParagonPct threshold.
[BST] Added condition to Focused paragon rotation to avoid spamming when group Paragon was active
Current behavior:
Group Paragon will be used when any group member's mana is below the class config setting "ParagonPct".
Focused Paragon will be used on the BST unless another target meets the criteria above and Group Paragon is on cooldown.
[ENC] Adjusted rotations so that low -level haste spells that were intended to be used on a pet before pet-specific buffs were …
> BST and ENC fixes and updates

- class_configs/bst_class_config.lua
Corrected new rotation name for Focused Paragon of Spirits, oversight from yesterday's push.
> Correction to bst_class_config.lua

- class_configs/enc_class_config.lua
- class_configs/pal_class_config.lua
- class_configs/shd_class_config.lua
[PAL] Corrected Tooltips in the Combat options.
[SHD] Added Shield Flash and updated the Tooltip to match PAL.
Shield Flash may have been an accidental deletion, as there is an empty space in the SHD file in the same location it is listed in the PAL file.
If its removal was intended, we can simply delete the FlashHP setting from SHD.
> PAL and SHD Tooltips/Shield Flash

- class_configs/clr_class_config.lua
- class_configs/dru_class_config.lua
- class_configs/enc_class_config.lua
- class_configs/shm_class_config.lua
[ENC] Updated aura entries so that the proper auras should be selected in all likely use cases: 
-Under Level 85, with or without Learner's selected (Twincast isn't available). 
-Level 85+, with or without Learner's selected, and with or without Auroria Mastery (second aura) AA.
Note: Auroria Mastery is available at level 81, but the code as written will not use a second aura until level 85 when Twincast is available.
Radiant Cure support
[SHM, DRU] Added Radiant Cure
[CLR] Improved handling with Radiant Cure
Using AAReady will simply return false if the PC doesn't have the AA and will not return when RC is on cooldown like CanUseAA.
> [ENC] Aura Fix

- class_configs/clr_class_config.lua
- class_configs/enc_class_config.lua
Swapped last entry for Cleric Aego and Symbol which was wrong
Fix for Cleric and Enchanter Aura that didnt got recognized as they have 1 Aura each that does not match with the Spell name.
And trying this Pull Request thing for the first time hoping I do it right.
> Fix for Cleric Aego/Symbol swap and Cleric/Ench Aura 

- class_configs/enc_class_config.lua
- class_configs/pal_class_config.lua
[PAL] Added barebones support for curing, currently only Radiant Cure is supported.
[PAL] Added barebones support for resurrection. Gift of Resurrection is the only source at this time, no items are included. Currently, Battle Rez is disabled in the Tank Mode regardless of the general setting "DoBattleRez".
Further implementation for both features is possible, but I feel more discussion or feedback is warranted.
[ENC] Swapped spell gems of unused spells to reduce remems during buff cycles.
[ENC] Added ManaDoT to dps rotation.
Further optimization likely needed, I am concentrating on small issues which give immediate returns.
> [PAL] Rez/Cures, [ENC] Spell Gem update

- class_configs/wiz_class_config.lua
This actually only applies to higher lvls, but how should it be handled not to clicked even when full mana?
chestclick only if mana is under harvest mana %
> Chestclick only if mana is under harvets %?

- utils/rgmercs_classloader.lua
if you comment out sections and try to import the config as a custom one, the commented out sections get ignored.
Added a flag to the config FullConfig = true/false if the flag is present and true then replace the default config with the custom one. otherwise use the mergeTables function.
example:
local _ClassConfig = {
_version          = "1.0 Beta",
_author           = "Derple",
['FullConfig'] = true,
> fix: import not honoring spells removed from sets.

- class_configs/dru_class_config.lua
- class_configs/mag_class_config.lua
- utils/rgmercs_utils.lua
[MAG] Added a function to handle autoinventory commands after item summons (to include a group command for modrods); disabled previous autoinventory function (slated for eventual removal).
[DRU] Fixed issue of spell table added for "Mana Mode" conflicting with original tables and causing spells not to be memorized.
[DRU] Made a pass of gem usage to try to closer align spells called in rotations and spells being memorized in Heal Mode.
> MAG  / DRU updates

- class_configs/dru_class_config.lua
Removed the AA Nature's Boon from downtime. Looks weird that it casts it when you start the Lua, even if everyone is full health and/or standing in safe places. 20min reuse. Its already in the Burn section.
> DRU - Removed Nature's Boon from downtime rotation

- class_configs/bst_class_config.lua
- modules/pull.lua
- utils/rgmercs_utils.lua
[pull] Allowed minimum mana to be 0%.
[utils] Added an interrupt for spell memorization if the PC enters combat (is directly attacked).
> Minor changes: pull and mem

- utils/rgmercs_config.lua
- utils/rgmercs_utils.lua
* toggle to force kill player pets on xtarget (disable if you have anyone charming)
* toggle to announce target "will announce target using kissassist format" useful when running a mixed automation group.
> couple options

- modules/pull.lua
now resets after populating the table with the path you selected so you can modify it needed without reloading rgmercs.
> fix selecting a path not letting you edit

- modules/movement.lua
- utils/rgmercs_config.lua
most emu servers don't have merc's, fellowship, or campfire's I want to say all but that may change so we just set the defaults for these to off. if the server happens to support them you can still enable.
> some emu defaults

- class_configs/brd_class_config.lua
- modules/charm.lua
- utils/rgmercs_utils.lua
RGMercUtils.ResolveDefaults also returns a boolean if we removed old settings and should save after.
tested with Charm Module but will apply to other modules soon.
added rest of the bard charms to the list. as the old list only went to lvl 65.
> save settings after removing depreciated

- class_configs/mag_class_config.lua
- class_configs/shd_class_config.lua
This will work for now. More may be necessary as they rear their head. 
Both tested with 120 mage/shd. Check recourse names and they seem to be consistent in these instances.
> Bandaid fix for recourses and f2p players with Rk. II spells

- class_configs/wiz_class_config.lua
Fixed active condition, adjusted condition to stop attempt spam in a niche case. (SelfBuffCheck has a .Stacks check so long as it isn't passed a string).
This can likely become the default for chest clicks that go to buff window, but some clicks may go to song window so I will need to check one by one.
on the active condition, buffactive will return false if passed nil, no need to check for item
> [WIZ] Minor fixes for chest click

- .vscode/settings.json
- class_configs/brd_class_config.lua
- class_configs/enc_class_config.lua
- modules/mez.lua
[ENC]
* Added a new mode ("ModernEra"), which updates the enchanter DPS rotation for modern live. Likely usable around level 90, and should come fully into it's own by 105ish.
* Moved emergency abilities (Stun AA, etc.) from DPS to their own rotation.
* Added Spell Proc Buff (for ModernEra)
* Separated Tash and (Crip)Slow into two rotations to improve the chances of them both being applied before we start DPS.
* Moved pet summon to its own rotation (and set it to not summon if we have enabled charm).
* Added autoinventory command after an Azure Crystal is summoned.
* Updated and retrofitted recent settings, functions and conditions
* Added Pull abilities
* Added a couple of options. Please note that ModernEra Mode has less options than typical and will ignore some configuration options …
> [ENC] Update, new mode added

- modules/charm.lua
- utils/rgmercs_events.lua
if you have dire charm enabled and auto lvl on it will lower dire charms max lvl by one below the target. THis way you can set it and let the game figure out your max until you buy a new tier.
> added event for target to high lvl to charm

- modules/loot.lua
issuing either `/rgl setitem [action]` or `/rgl setglobalitem [action]` will auto inventory
If the action is destroy, we will /destroy the item instead of putting it back into inventory
> feat: setitem and setglobalitem tweaks

- utils/rgmercs_config.lua
- utils/rgmercs_utils.lua
* UseSong now has the adjustments to song clipping intended to release alongside the bard revamp. Expect 200-300ms improvement per song.
* Fix for UseSpell and UseAA relying on imprecise data for cast times, AA's with cast times should no longer clip early (further tuning may be needed on the value).
> [utils] UseSong/Spell/AA Updates

- lib/lootnscoot/loot_lib.lua
- modules/loot.lua
cleaned up some ini stuff
added back in the save to ini functions. for when looting new items or auto sell/tribute also writes to the ini if we add items to global or buy
Does not write to the file when we modify or delete an item. that stays in our local rgmers settings we  use. this way we do not pollute the loot.ini
> removed autoloot setting

- lib/lootnscoot/loot_hist.lua
- lib/lootnscoot/loot_lib.lua
- modules/loot.lua
Migrated the loot tables to an SQL DB with tables for (Global_Items,  Normal_Items)
This allows the data to be shared by all of the characters without to many conflicts.
If you edit or add anything on the driver and save the settings you can issue /rgl lootreload on all characters to reload from the DB. 
The **FIRST TIME** you run this after this update, **ONLY** Load RGMercs Lua On **ONE Character** to build the DB. 
This Could take a couple seconds to create and populate the database. (_especially if your loot.ini is large_)
After you have the database created you can load as many toons as you would like. 
* Check for loot DB (saved by server name cause emu servers can have different loot)
* If the DB is missing we create it and the 2 tables.
* If we created a new Database
* then load …
> Loot tables to SQL DB

- lib/lootnscoot/loot_lib.lua
- modules/loot.lua
Lets not auto import the ini on the initial load if the database doesn't exist. 
Instead we will create the tables if they do not exist but to import you must issue
`/rgl lootupdate` or `/rgl lootimport`
Added a warn message about this if you do not already have a database created.
fix destroy and tribute settings updating.
fix reporting showing all items as global.
> Loot fixes and changes

- lib/lootnscoot/loot_lib.lua
- modules/loot.lua
- modules/movement.lua
- utils/rgmercs_config.lua
* also fixed the bags full check so you will still loot stackable items if you have a stack started and space for more.  (i broke that a lone time ago and no one noticed except Derple)
* Limited the table sizes on the loot tables and made the table itself scrollable instead of the whole window.
* fix warning message about DoMercenary being in 2 locations when on emu.
> loot check when tributing stackable items

- lib/lootnscoot/loot_lib.lua
this should prevent the lockup when importing a large loot.ini
> importing loot.ini to db is no batched

- lib/lootnscoot/loot_lib.lua
- modules/loot.lua
When enabled we will loot our own corpses first if near.  This does not check for Rez.
On or OFF we will not loot npc's if we have a corpse near because we want to make sure we have bags to put the loot into.
> LootMyCorpse toggle

- class_configs/pal_class_config.lua
- class_configs/shd_class_config.lua
- class_configs/wiz_class_config.lua
- utils/rgmercs_utils.lua
[SHD]
* AE Taunts will no longer activate on a single target unless they are configured to do so (setting AE Taunt Count to "1" should use them when aggro is lost/not yet established).
[WIZ]
* Loosened overly stringent conditions on Harvest Spell usage.
[PAL]
* Added support for the Undead Proc spells:
* * Under Level 45 (when the first all-target ("Fury") proc is available), these spells will always be used.
* * Once we have a Fury proc, we will prefer it unless the option "Use Undead Proc" is selected.
* * Once our Unity buff includes Fury, we will cease to use the Undead Proc entirely, regardless of the above option.
> Class Updates

- class_configs/Live - Experimental/nec_class_config.lua
[NEC] - Modern Era Mode
* Experimental Config, only this mode is enabled (select "Experimental" in your NEC's menu).
* Best at Level 110+, but likely still effective at 90 (perhaps lower).
* Largely aimed at group play:
* * Removed some of the long-duration, low-DPS dots from the lineup.
* * Replaced them with on-demand damage that is used once the HPStopDot thresholds are crossed (nukes and swarm pet).
* * Gemmed short-duration buffs to allow ease of maintenance in rapid pulling scenarios.
Whether this config becomes simply a mode in the default or something more is undecided. Let us know what you think! The core of this config has served me well for hundreds of hours of use and I'd love to hear from you.
> Added experimental config: Modern Era Necromancer

- class_configs/Live/brd_class_config.lua
- utils/rgmercs_binds.lua
* Usage: /rgl usemap maptype mapname targetID
* * Maptype: spell, song, aa, item, disc
* * Mapname: Entry name as shown in rotation window (e.g, FireSpell3, MezSpell)
* * TargetID: Optional, will use the current target and fallback to targeting yourself if you don't have one.
This may be handy to hotbutton abilities that are often used manually but updated constantly as you level.
* Examples
* * (SK) /rgl usemap disc Mantle : uses your current Mantle Disc
* * (SHM)/dg shm /rgl usemap spell GroupRenewalHoT $\{Me.ID} : Tell your shaman to cast his group HoT on himself
Smart use of hotbuttons could have your driver telling your bard to calm the driver's target, your enchanter to mez the same,  having "preburn" buttons just before a big pull, etc.
> New command: /rgl usemap (manually cast/use by rotation entry name).

- class_configs/Live - Experimental/clr_class_config.lua
- class_configs/Live - Experimental/pal_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
* Some spell entries designed for early recast for 100% uptime (temp HP, etc) weren't recasting until expiry.
> Fix for certain spells not recasting prior to expiration

- modules/class.lua
* Disabled while we examine an error in the underlying function. Manual copying is unimpeded.
> Temporarily disabled custom config creation via UI button.

- class_configs/Live - Experimental/clr_class_config.lua
- class_configs/Live - Experimental/dru_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
- utils/targeting.lua
* Added check to ensure we are grouped with the target before using group heals for a single target in the main healing rotations (e.g, Shaman Recourse).
* * Improves X-Target/OAL healing.
* * This affects SHM Live/Laz, CLR/DRU Live Experimental.
* [CLR] Added RoS VP Hammer support to Live - Exp config.
> Healer Updates

- class_configs/Live - Experimental/dru_class_config.lua
- class_configs/Live/dru_class_config.lua
* Please note that we have no plans to separate non-lev and lev versions of movebuffs at this time due to the drastic speed differences. If there are any issues with movebuffs because of this, or if you experience "buff-wars" with another class that also uses movebuffs, simply disable the one you don't wish to use.
> Additional adjustment of movement buff handling for druid configs

- class_configs/Live - Experimental/pal_class_config.lua
- utils/casting.lua
Adjusted BuffRezables to stop all group buff use if not enabled and there is a corpse of *any* group member in range.
Current behavior is one PC will be rezzed, and while the rez is on cooldown, we will often buff them. The rez will come back up, but we are still busy buffing rezzed dude, and we don't rez dead dude. Then we rez dead dude, and do the entire thing again, because now HE needs buffs too. Etc. Better than before, but still has room for improvement.
This behavior should be fixed with this change, and we should save time and mana.
> Changed BuffRezables behavior

- utils/config.lua
Users will not have to fight automation or pause to med/sit/camp unless they elect to do so.
> Changed default for [StandWhenDone] (aka, force stand) to false

- utils/casting.lua
* We should no longer attempt to sit if we are being beat on when combat med is enabled. Further adjustment of aggro values may be necessary.
> Added an aggro check to meditation during combat

- init.lua
- modules/charm.lua
- modules/class.lua
- modules/drag.lua
- modules/experience.lua
- modules/faq.lua
- modules/mez.lua
- modules/movement.lua
- modules/named.lua
- modules/performance.lua
- modules/pull.lua
- modules/travel.lua
- utils/binds.lua
- utils/config.lua
- utils/targeting.lua
- utils/ui.lua
* Reorganized and sorted elements and features that have been "tacked on" over time.
* Improved pop-out function and aesthetics.
* Added ease-of-use button for /rgl burnnow.
* Hid the console behind a collapsing header.
* Organized all config windows to be at the bottom of their respective windows.
* Moved pertinent information closer to the top of each window.
* Moved the class config selection to the class module tab.
* Added indents under some collapsing headers for uniformity.
* Added tooltips to some UI elements (WIP, intend to add more).
> Minor UI Overhaul

- class_configs/Live - Experimental/clr_class_config.lua
- class_configs/Live - Experimental/dru_class_config.lua
- class_configs/Live - Experimental/pal_class_config.lua
- class_configs/Live/clr_class_config.lua
- class_configs/Live/dru_class_config.lua
- class_configs/Live/pal_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/clr_class_config.lua
- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/pal_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
* Tightened conditions for Rez functions:
* * We should no longer target a corpse until a rez action is ready
* * Corpse summoning should no longer occur unless a rez action is ready
* Added PAL rez spells to all PAL configs.
* Added DRU rez spells to Laz config.
* CLR will now use Larger Reviviscence (6 person rez) if three or more group/OAL corpses are present.
Numerous PCs were harmed during the making of these changes.
> Improved Resurrection Handling

- class_configs/Live/enc_class_config.lua
- modules/mez.lua
[ENC]
* Live : Combined twincast mez options to eliminate conflicts between mode settings.
* * Twincast mez options will now be respected regardless of mode.
> Minor Enchanter Update

- utils/casting.lua
* Corrected an invalid comparison in a delay callback during the spell-casting process.
> Fix for potential crash during spell cast (Thanks Free_Sid and LorDeth!)

- init.lua
- modules/charm.lua
- modules/class.lua
- modules/mez.lua
- modules/movement.lua
- modules/pull.lua
- utils/casting.lua
- utils/classloader.lua
- utils/config.lua
- utils/event_handlers.lua
* Most settings are now saved on a per-class basis.
* * Exceptions exist where settings aren't likely to be different, e.g, Drag Module settings. Feedback is welcome.
* The process of a config change should occur automatically; no manual input should be required.
* Pausing the script prior to swapping is not required, but is recommended.
* * Please use the built-in pause feature, do not use /lua pause.
* * If the script is not paused, expect a small delay as the last rotation is processed; all queued actions should be aborted.
* * * We largely coded this as a fallback measure, it is recommended to pause the script before swapping.
* * * Please report any issues noted during this process!
> Full Persona Support Added

- class_configs/Live - Experimental/nec_class_config.lua
- class_configs/Live/bst_class_config.lua
- class_configs/Live/enc_class_config.lua
- class_configs/Live/mag_class_config.lua
- class_configs/Live/nec_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/bst_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/mag_class_config.lua
- class_configs/Project Lazarus/nec_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
PCs will no longer summon pets if they have a corpse in the vicinity (unless the "Buff Rezables" option is selected).
Fixes #382
> Pets will no longer be summoned by default while awaiting Rez.

- init.lua
- modules/charm.lua
- modules/mez.lua
- modules/movement.lua
- utils/casting.lua
- utils/combat.lua
- utils/ui.lua
* Corrected implementation SetTarget() variables in our assist functions, we should now wait for buffs to populate before checking whether a target is OkayToEngage().
* * Speculative fix for PC's sometimes acting as if a target is Mezzed when the mez has already been broken, causing repeated target clears.
* Changed several instances of checking for an .ID() while casting to simply checking for .Casting() (I believe this is a macro holdover).
> Minor "under the hood" adjustments

- modules/class.lua
* We will now reset the Group Buff rotation timer when a rez is attempted to facilitate faster rebuffing.
* The /rgl rebuff command will reset relevant rotation timers, allowing them to be checked again immediately. It will not force any particular buff to be cast.
* * Affected Timers: Slow Downtime, Group Buff, Pet Buff.
> New command: /rgl rebuff

- class_configs/Live - Experimental/clr_class_config.lua
- class_configs/Live/clr_class_config.lua
- class_configs/Project Lazarus/clr_class_config.lua
- utils/casting.lua
* Added support to pass a spell ID to check against in GroupBuffCheck()
* * ID is optional and should be the third variable (See AegoBuff entry in any Cleric config for example).
* * This was added to handle situations where the EQ spell list contained two or more spells with the same name, and should only be required on a case-by-case basis.
* While there is a strong case to move to the sole use of ID's in the function, this fix is completely compatible with existing custom configs.
> Group Buff Check Update

- utils/casting.lua
* Corrected occasional duplicate spell casting when one or more effects did not take hold due to stacking.
> Minor Bugfixes

- modules/class.lua
- utils/casting.lua
- utils/config.lua
This is an "Alpha" feature that may see heavy revision at a later date.  Currently, only detrimental spells against our combat target are supported (initial support is largely aimed at the numerous "DD Clickies" that are found on Project Lazarus, but stacking checks for debuffs are present). Feedback is requested, especially feedback concerning special-use items, regardless of server.
* Added support for "clickies" in combat:
* * Settings can be found in the existing "Clickies" tab.
* * If enabled, we will check the list for a clicky to use every 10 seconds (to ensure we don't step on our normal rotations). This delay value is user-adjustable as an advanced setting.
* * After one available clicky is used, normal rotations will be resumed until the next check.
> Added Combat Clickies

- class_configs/Live - Experimental/dru_class_config.lua
- class_configs/Live - Experimental/wiz_class_config.lua
- class_configs/Live/bst_class_config.lua
- class_configs/Live/dru_class_config.lua
- class_configs/Live/enc_class_config.lua
- class_configs/Live/mag_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Live/war_class_config.lua
- class_configs/Project Lazarus/bst_class_config.lua
- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/mag_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
- class_configs/Project Lazarus/war_class_config.lua
- modules/class.lua
- utils/item_manager.lua
Known Issue: Enabling "Do Destroy" in the loot module when using the bard instrument swap feature may cause a rare condition in which an item is deleted. Please don't use them together. Fix is in work to lock them out from each other.
* [ENC] (Laz): Added Unified Alacrity (Thanks Robban!)
* Under the hood change for AA debuff checks.
* Fixed missing setting reporting error in combat clicky use.
* Slightly adjusted bard item swap code.
> Various Updates

- class_configs/Live - Experimental/dru_class_config.lua
- class_configs/Live/dru_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
- utils/casting.lua
- utils/movement.lua
* Rezzers will no longer respect certain meditation settings if a group/OA corpse is present.
* Added corpse check to the Shaman "Slow Downtime" rotation.
* Fixed a condition in which the Group Buff rotation would still process when the caster's corpse was the only one present.
Other minor adjustments:
* Reduced the delay between stick adjustments. Further adjustment may be warranted after more testing and feedback.
* Updated Call of the Wild usage to make sure it is never used on the caster's corpse.
> Rez Fixes (Thanks scvone!)

- class_configs/Beta/mnk_class_config.lua
- class_configs/Beta/rog_class_config.lua
- class_configs/Live/bst_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/war_class_config.lua
- class_configs/Project Lazarus/bst_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- class_configs/Project Lazarus/war_class_config.lua
All: Added support for AE abilities, to include target count and optional safety (see Note) checks.
*Laz: Added initial support new/revamped spells (Grasp of Lhranc, Spear of Decay/Muram).
* * Gem and rotation place may be adjusted, feedback welcome.
* Live: Added support for Insidious Line (AE Tap).
Special Note: Safety checks will check for "aggroable" mobs in proximity. These abilities, as annotated in the settings, can and will break Mez. Unfortunately, "Mez checks" or similar for AE Damage is not on the current planned feature list.
> SHD Updates

- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/mag_class_config.lua
- class_configs/Project Lazarus/nec_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
* Added (optional) support for the extended series of Arcanum AA.
* * Empowered/Enlightened/Acute will be used in the normal combat routine if one isn't currently running.
* * The original "Focus of Arcanum" will be used  in a burn on a named irrespective of the above.
> Laz: Arcanum Weave (Thanks sputnik!)

- lib/lootnscoot/.gitignore
- lib/lootnscoot/init.lua
- lib/lootnscoot/init.lua.bak
- lib/lootnscoot/lib/Write.lua
- lib/lootnscoot/loot_hist.lua
- modules/loot.lua
You can now Bulk set rules for entire pages of items
refined the number of items to show down to increments of 10 to help.
you can now toggle the INFO messages off.
these also now go to the lootnscoot console and not the main mq console
actors should properly communicate with standalone and mercs clients on the same machine.
> bulk edit, toggle INFO messages off, Actors work

- class_configs/Cleric Beta - Live/clr_class_config.lua
- class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua
- utils/event_handlers.lua
* Simplified hp buff checks (and removed Saint's Unity from the Laz config).
* * Complexity of checks was not justified compared to the rarity of us benefitting from them.
*Slightly adjusted a too-far value as a string-on to yesterdays event handler update.
> Cleric Beta Self HP-Buff adjustment (Thanks MaxD!)

- modules/pull.lua
Added support for specifying a max level difference for "Deep Red" mobs. (Default: 6)
> Pull Update

- class_configs/Live/shd_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
* Rearranged Carapace and Mantle tables for sensical Timer 5 use until Carapace transitions to Timer 11 at Level 88.
> SHD Update

- class_configs/Cleric Beta - Live/clr_class_config.lua
- class_configs/Cleric Beta - Project Lazarus/clr_class_config.lua
* Added single-slot AC Buff (optional).
* Added support for using both Aego and Symbol for party members who block certain buffs.
* Added low level Spell Haste buffs.
* Added single-target Vie buffs (along with a setting to govern Vie use).
* Added proper usage of Shining buff on Tank once it is available.
* Arranged gems to accommodate new options.
> Cleric Beta Pt 2

- class_configs/Live/enc_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- utils/config.lua
* [Laz] Added support for a group-wide /autoinventory after crystal summon.
* [All] For simplicity, Azure Mind Crystals are now treated as mod rods for all intents and purposes, since their use was already tied to the same settings.
* * Removed the individual entries to use the crystals from ENC configs.
> ENC - Azure Mind Crystal

- class_configs/Alpha (Live)/dru_class_config.lua
- class_configs/Alpha (Live)/wiz_class_config.lua
- class_configs/Alpha (Project Lazarus)/dru_class_config.lua
- class_configs/Live/bst_class_config.lua
- class_configs/Live/clr_class_config.lua
- class_configs/Live/enc_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/bst_class_config.lua
- class_configs/Project Lazarus/clr_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
- utils/casting.lua
* Simplified Gem Timer checks in Class Configs
* * Removed CastReady helper function calls from class configs in favor of GemReady, which does not require passing RankName.
* * These changes are backwards-compatible (custom config users can contine to use CastReady).
> GemReady function

- class_configs/Live/rng_class_config.lua
- class_configs/Project Lazarus/rng_class_config.lua
* We will now check to make sure Epics are present before trying to use them.
* Temporarily disabled autofire command in ranger custom combat nav while Do Melee is set to avoid autofire/autoattack interaction issues on emu servers.
> Ranger Update

- utils/combat.lua
***No NPCs named Lady Mirenilla were harmed in the troubleshooting of this error!***
* Fix for a peer check returning "nil" causing the autotarget to be set to a spawn whose name contained those letters.
> Outside Assist Fix (Thanks Lisie!)

- class_configs/Live/pal_class_config.lua
- class_configs/Project Lazarus/pal_class_config.lua
- utils/combat.lua
* Adjusted Paladin Heal Rotations  (Live and Laz) to better reflect modern defaults and code.
* * Eliminated Light Heal Rotation
* * * "LightHeal" has been moved to the Main Heal rotation.
* * Added Group Heal Rotation and shuffled abilities as appropriate.
> Paladin Heal Rotations (Thanks Redfrog!)

- class_configs/Live/mag_class_config.lua
- class_configs/Project Lazarus/mag_class_config.lua
All Configs, while on Emu servers:
* To avoid conflicts with corpse-looting, we will no longer summon a mod rod if we detect a party member has nothing equipped in the Main Hand.
> ModRod Update

- lib/lootnscoot/init.lua
- modules/loot.lua
added always global setting
turning this on will duplicate your new items into Global Rules
this will happen when looting and when acknowledging the new items list.
fixed quest items not populating class designations properly
> fix: classes loading, feat: AlwaysGlobal setting

- class_configs/Live/shd_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
* Live: Re-ordered rotations and slightly adjusted how we use and check Emergency HP thresholds to (hopefully) make defenses a little snappier.
* Laz: Did the above and removed rotation entries for non-present abilities and spells.
* * Started process of removing spells not present on the server from the action tables.
> SHD Config Updates

- modules/class.lua
* Adjusted xtarget-based moveback when we detect an xthater behind us.
* * Removed the delay after we issue this command, as this should (speculatively) no longer be required due to the current movement checks embedded in rotations.
> Tank MoveBack Update

- utils/combat.lua
* Adjusted target scan to prevent a condition in which we assigned the initial autotarget incorrectly, which could lead to an infinite loop under some setting combinations. Special thanks to sputnik for helping track this one down!
* Fixed some log code that could potentially return nil while intentionally trying to reproduce infinite loops.
> TargetScan Update

- class_configs/Project Lazarus/enc_class_config.lua
- modules/class.lua
* [ENC] Mind Crystal Improvements:
* * Added entry for Sanguine Mind Crystal.
* * Checks for crystals needed will now include the entire group.
* * Added the ability to adjust the ms delay before an /autoinv is issued to the group after summon (similar to MAG).
* * * Please note that /autoinv can fail on PCs taking certain other actions, and your enchanter isn't to blame for this.
* [All] Added initial support for Sanguine Crystal use.
* * Crystals will be used in-combat, when we detect health under your class-specific Emergency Start settings (with 45% as a fallback for classes who don't currently have the setting).
As a note, Mind Crystals were added to be used under the same conditions as ModRods in a previous update.
> Laz - Mind Crystal Update

- class_configs/Alpha (Live)/dru_class_config.lua
- class_configs/Alpha (Live)/nec_class_config.lua
- class_configs/Alpha (Live)/pal_class_config.lua
- class_configs/Alpha (Project Lazarus)/dru_class_config.lua
- class_configs/Live/clr_class_config.lua
- class_configs/Live/dru_class_config.lua
- class_configs/Live/nec_class_config.lua
- class_configs/Live/pal_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/clr_class_config.lua
- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/nec_class_config.lua
- class_configs/Project Lazarus/pal_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
- modules/class.lua
- utils/casting.lua
- utils/config.lua
- utils/event_handlers.lua
***UPDATE: All DoRez functions now converted to use this system.***
On Emu, corpses persist past resurrection. Because of this, if the corpse isn't looted in a timely manner, we can find ourselves in a loop of a healer casting a rez every few seconds, and the target chain-accepting due to mq2rez settings.
Any corpse that has already been rezzed will indicate so when conned.
This update addresses the issue like so:
* During FooCheckAndRez, we will check to ensure the corpse ID is not on a table of already rezzed corpses.
* * If it is, we abort. If it is not...
* We will start to execute our DoRez function.
* * If a valid rez ability for combat state is not available, we abort. If it is...
* We will make a check to see if we are on Emu.
* * If not, we will summon the corpse (if it isn't …
> Emu Rez Changes (Cleric Prototype)

- class_configs/Project Lazarus/mag_class_config.lua
- class_configs/Project Lazarus/wiz_class_config.lua
* Added basic support for a PBAE rotation at level 70 (comprising of Wind of the Desert and Scintillation).
* Removed many entries that are not present on Lazarus.
* Added a combo-box option for the level 70 Swarmpet Spell (Off/Named Only/Always).
* Adjusted spell gem selections.
* Adjusted DPS rotation switch to occur based on scribing "Spear of Ro".
> MAG (Laz) Update

- lib/lootnscoot/init.lua
- modules/loot.lua
- utils/casting.lua
Casting check
should no longer run to loot mid cast.
Corpse Check adjusted now checks for exact name when searching for player corpse. this should prevent selecting wrong corpse when multiple PC's start with the same name ex. Derple Derplemag Derpleclr
bank changes and some other fixes. 
the bank tradeskills flag will no longer auto flag items to bank
Instead it will be checked when issuing the bank command.
When banking:
check rules and if its 'Bank' toss it into the bank
if the rule is not Global or Personal then check if the item is a TS item, and if we have Bank TS enabled.
if both are true then bank it.
this way we don't have rules flip flopping from this setting. and it still serves a purpose for items without overrides in global or personal rules tables.
This still allows you to …
> brings up to current

- utils/casting.lua
We should now return to our seats if we perform an action while already meditating and have yet to reach our "stop" percentages (even when we are now above the "start" percentages).
> AutoMed update

- class_configs/Live/clr_class_config.lua
- class_configs/Project Lazarus/clr_class_config.lua
- utils/casting.lua
* When a /con message isn't received on emu, we will now warn the player but allow the "already rezzed" check to continue to prevent possible conflict with combat rezzing.
* Corrected an issue where a cleric may not use appropriate rez actions if in the "debuffed" combat state.
> Rez Update

- utils/config.lua
- utils/rotation.lua
Expanded support for spell memorization after the last gem is used for buffs:
* New options are "Mem Loadout Spell" (default), "Mem Previous Spell" (default old behavior), and "Do Nothing". Please see the tooltip in game for more details. This option can be found in the main config options on the Spells/Abils tab.
> Buff Gem Use Update

- class_configs/Live/mag_class_config.lua
- class_configs/Project Lazarus/mag_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
[SHD-Laz]
* Added an entry to cancel Visage of Death when health is critically low during downtime.
[MAG]
* Magicians will now ignore missing modrods on pure melee classes.
> Minor Config Updates

- class_configs/Project Lazarus/mag_class_config.lua
- utils/casting.lua
* Re-added the option to pass a specific ID to the Group Buff Check to solve the issue of identically named book and AA spells being crossed.
* [MAG-Laz] Added PetHeal AA.
> Buff Check Update

- class_configs/Alpha (Live)/pal_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/war_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- class_configs/Project Lazarus/war_class_config.lua
* Increased performance of defensive disc checks and AE taunt checks (where safe AE taunt is disabled).
[SHD-Live]
* Refactored rotations for performance and combat smoothing. While no abilities were added or removed, how or when they are checked may have been.
* Adjusted the HP thresholds used for defenses:
* * Defense Start : When we will use defensive discs (note, using them based off of target count is still an option).
* * Emergency Start: When we will use the next tier of defensive abilities such as Shield Flash, Chest click, and stop mana checks on Lifetaps.
* * Critical HP: When we will use abilities like Deflection or Leech Touch. 
* * Hitting these thresholds will increasingly cut out various offensive rotations to improve reaction time.
> Tank AE Update, SHD (Live) Update

- class_configs/Project Lazarus/clr_class_config.lua
- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/mag_class_config.lua
- class_configs/Project Lazarus/wiz_class_config.lua
[CLR]- Larger Incremental Update
* Refactored curing as the grouphealcure doesn't hold up well at these levels.
* * Added individual options to keep poi/dis/curse cures memmed.
* Added support for the custom TwinHealStunNukeThing
* Removed spells unavailable on Lazarus.
* * #570
* Split Do HoT option into Single and Group Elixir options.
* * Added option to attempt to maintain Group Elixir uptime during combat.
* Removed unused rotations from Live Config.
* Moved to the priority-based spell list.
* Reorganized settings and categories.
[DRU]
* Slightly reordered spell list.
* Added entry for Protection of the Direwood.
[ENC]
* Reenabled Self Stasis, added a post activate to remove the stasis buff.
[MAG]
* Added entry for Replenish Companion.
[WIZ]
* Added entry for Mana Blast.
* Added …
> Laz Config Updates

- class_configs/Alpha (Live)/dru_class_config.lua
- class_configs/Live/dru_class_config.lua
- class_configs/Live/shm_class_config.lua
Refactored DRU/SHM Twinheal nukes to use a custom function so the autotarget can remain the rotation target.
> Live TwinHeal Update

- class_configs/Live/clr_class_config.lua
- class_configs/Project Lazarus/clr_class_config.lua
- extras/contributors.lua
This was erroneously added as a normal heal I guess. It's in HoT section as well.
> Remove HoT spell from normal heal list

- class_configs/Project Lazarus/dru_class_config.lua
We will now attempt to use Wrath of the Wild on any group member but the MA; this AA has a small chance of fade and could remove the tank from combat.
> Dru Laz Update

- class_configs/Alpha (Live)/dru_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/wiz_class_config.lua
- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- class_configs/Project Lazarus/wiz_class_config.lua
By default, we will no longer attempt to snare named mobs (or mobs the user has designated as such).
> Snare Adjustment

- class_configs/Live/brd_class_config.lua
- modules/mez.lua
- utils/casting.lua
* Fixed an issue in which discs, aa and items would not always properly report ready for a Bard.
* We will now properly ignore Crescendo if the gem is in cooldown.
* Speculative fix for occasionally locking gems when an Insult is cancelled at precisely the wrong moment.
> Bard Adjustments

- class_configs/Alpha (Live)/dru_class_config.lua
- class_configs/Live/dru_class_config.lua
- class_configs/Live/enc_class_config.lua
- class_configs/Live/rng_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/rng_class_config.lua
- utils/casting.lua
* Bard item/aa/disc ready checks will no longer fail while they are singing if the cast time is instant.
* Speculative fix for Insults occasionally causing stuck bard gems.
* Standardized logging level in use functions for spells/AA/discs/songs/items.
* Various Classes: Corrected ready checks for long recast spells (thanks mackal!)
* RNG: Fix for healing rotation functions (thanks sputnik!)
> Casting, Config Updates

- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/shd_class_config.lua
- modules/loot.lua
- modules/pull.lua
* [pull] Fix for nil crash when Group Watch is enabled for non-existent party members (thanks mhoney71!)
* [ENC-Laz] Fix for spire check when not in a group.
* [SHD-Laz] We will now refresh the skin buff as needed if in combat with a named mob.
* [loot] Exposed the maximum amount of time we will allow LNS to process corpse looting in one iteration as a setting. (Default: 5 seconds, the original hardcoded value).
> Minor Updates

- class_configs/Live/brd_class_config.lua
- class_configs/Live/shm_class_config.lua
- utils/casting.lua
- utils/event_handlers.lua
* Fixed a bug in AA checks that was causing some AA to be bypassed once a cast has started. (Thanks guest01!)
* Further adjusted bard singing check to better handle song cancellation.
* [BRD(Live] - Removed support for Dreadstone/SoB items. These can now be used on the clickies tab if desired.
* [SHM(Live] - Corrected a case in which certain spells would be memorized at inopportune times in hybrid mode (thanks guest01!)
* Added a nil safety in a target range check for the too far handlers. (thanks Coldblooded!)
> Casting Fix

- utils/casting.lua
Adjusted group buff checks to help prioritize drivers and reduce situations where buffers are left behind:
* The detected foreground client window will check itself before other group members; any background windows will check the rest of the group first.
> Group Buff Update

- class_configs/Project Lazarus/bst_class_config.lua
- class_configs/Project Lazarus/wiz_class_config.lua
[BST-Laz]
* We will now respect the setting to DoT only named.
* Hardcoded workaround for improper stacking reporting for Spiritual Vitality. 
[WIZ-Laz]
* Consolidated all Mana Burn style AA and limited their use to named.
> BST/WIZ (Laz)

- utils/movement.lua
Slight adjustment to default stick at high target height values for non-tanks (Alleviates some issues with rooted mobs).
> Stick Update

- utils/casting.lua
* Refactored PeerBuffCheck to properly alert us when we identify a PC as an in-range peer, yet they do not respond to the query (Example: PC LD).
> Group Buff Update (Thanks Lidori!)

- class_configs/Beta (Project Lazarus)/pal_class_config.lua
- modules/loot.lua
* The option to load LNS is now false by default, correcting the issue of us waiting for a script that may not be present.
> Loot Update (thanks pleasant!)

- modules/class.lua
- utils/combat.lua
- utils/config.lua
* Assisting by using RA targets above the first is now supported in the RaidAssistTarget setting.
* The Assist Outside setting now strictly covers treating the top valid PC on the Outside Assist List (OAL) as the MA.
* * Removed the duplicate "Assist  Outside" setting entry from the engage tab.
* Heal Outside (default: true) will control whether we heal PCs on xtarget, and whether we check for rezzes outside of our group.
* * OOG rez checks encompass raid members, guild mates, PCs on the OAL and dannet peers.
> Raid Improvements

- class_configs/Project Lazarus/bst_class_config.lua
- class_configs/Project Lazarus/enc_class_config.lua
- class_configs/Project Lazarus/pal_class_config.lua
- class_configs/Project Lazarus/wiz_class_config.lua
- utils/casting.lua
[casting]
* The default retrycount for spells and abilities has been lowered to two (from three).
[Laz Adjustments]
* Added Tome of Nife's Mercy entries for classes that can use it. The item will not show in rotations unless you have a copy; loadout rescan will be required if you acquire one mid-playsession.
* Added helper function for LowManaCount that accounts for the PC not reporting his own low mana in the Group.LowMana check on emu.
* Rolled out basic support for Forsaken Fungus Covered Scale Tunic for a couple of classes. WIP.
> Casting, Laz Adjustments

- class_configs/Live/wiz_class_config.lua
* Smoothed transition between rotations at level 71 based on currently scribed spells.
* *The intent of the change is so someone can complete a leveling session before they stop and purchase spells. RGMercs devs do not encourage, suggest, recommend, advise, counsel or otherwise imply approval of the use of 20-level old spells.
> WIZ(Live) Update

- class_configs/Alpha (Live)/dru_class_config.lua
- class_configs/Live/clr_class_config.lua
- class_configs/Live/dru_class_config.lua
- class_configs/Live/mag_class_config.lua
- class_configs/Live/shm_class_config.lua
- class_configs/Project Lazarus/bst_class_config.lua
- class_configs/Project Lazarus/clr_class_config.lua
- class_configs/Project Lazarus/dru_class_config.lua
- class_configs/Project Lazarus/pal_class_config.lua
- class_configs/Project Lazarus/shm_class_config.lua
- utils/combat.lua
- utils/config.lua
* Default class configs for healers (inc. PAL)  have been adjusted to no longer use "big heal" rotations on pets (if pet healing is enabled in the first place).
* * Hybrid and pet class healing has not been adjusted.
* Made minor adjustments to pet heal settings and tooltips for clarity.
> Pet Heal Adjustment

- class_configs/Alpha (Live)/pal_class_config.lua
- class_configs/Live/pal_class_config.lua
- class_configs/Live/shd_class_config.lua
- class_configs/Live/war_class_config.lua
- class_configs/Project Lazarus/mag_class_config.lua
- class_configs/Project Lazarus/nec_class_config.lua
- class_configs/Project Lazarus/pal_class_config.lua
- class_configs/Project Lazarus/wiz_class_config.lua
- modules/clickies.lua
Project Lazarus users: We are replacing some hardcoded "heal clicky" support and you should have a look at these update notes.
* Added support for server/environment-specific default recommended clickies on the clickies tab:
* * These clickies will be present on load for new users.
* * Current users can add these clickies any time through a button in the UI.
* * Live/Test clickies are a WIP and feedback is requested.
* * Laz clickies include Orb of Shadows, Sanguine Mind Crystals, and the Forsaken Fungus Covered Scale Tunic.
* Removed the above clickies from hardcoded positions in default class configs.
* Removed Huntsman's quiver from default live configs.
> Server-Specific Default Clickies

- modules/class.lua
- ui/options.lua
- utils/combat.lua
- utils/config.lua
Improved the MA Target Scan algorithm and added the following settings:
* Named Priority (Named, No Preference, Non-Named). (default: Named)
* HP% Priority (Lowest, No Preference, Highest). (default: Lowest)
* Aggro Scan: Prioritizing targets not aggroed on the PC is now optional. (default: true)
* Area Scan Fallback: Rework of "Only Scan XT". Will use spawnsearches as a fallback if no targets are on XT. Helps with some emulation XT bugs (default: false (live/test), true (emu environments).
*  Targeting options can be found in the combat group.
Bug Fixes
* Fixed a long-standing bug in tank moveback. You should now see consistent moveback again when targets edge behind the tank, if enabled.
* We will no longer rescan loadouts in combat. This should reduce the number of times we abort …
> Target Scan Update, Bug Fixes

- modules/class.lua
/rgl useitem will queue the use of the specified item to be processed in the mercs environment. Example:
/rgl useitem "Awesome Army's Armguards of Amazing Alliteration"
> Added /rgl useitem
